# this a temporary script to load all functions in the package

# loading packages
library(doParallel)
library(foreach)
library(magrittr)
library(reshape2)
library(purrr)
library(furrr)
library(dplyr)
library(DBI)
library(RSQLite)
library(dbplyr)

library(ggplot2)
library(ggseqlogo)
library(pheatmap)
library(RColorBrewer)
library(DescTools)
library(protr)
library(fastmatch)
library(stringr)

library(seqinr, quietly = T)
library(data.table, quietly = T)
library(Rfast, quietly = T)

# source("AnalyzeThis.R") # contains unfinshed functions, commented out for now
source("GenerateXmers_perl_wrapper.R")
source("GetNetMHCIIpan.R")
source("GetNetMHCpan.R")
source("IsValidPeptide.R")
source("LogIt.R")
source("ReduceEpitopeSimilarity.R")
source("RunCommand.R")
source("SimplifyAlleles.R")
source("RunNetMHCIIpan.R")
source("RunNetMHCpan.R")
source("CreateRecognMatrix.R")
source("db_playground/functions.R")